[package]
name = "rust_sudoku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "1.0.0"

[[bin]]
name = "rust_sudoku"
path = "main.rs"
